datos_heroes = {
    "Akai": ["Intrépido", "Altar del Dragón"],
    "Aldous": ["Portador del Amanecer", "Golpeador"],
    "Alpha": ["Tejedor de Sombras", "Maestro de Armas"],
    "Angela": ["Hadanacido", "Mago"],
    "Argus": ["Juraperdición", "Maestro de Armas"],
    "Atlas": ["Valle del Norte", "Defensor"],
    "Aurora": ["Valle del Norte", "Mago"],
    "Badang": ["Señor de Ascuas", "Golpeador"],
    "Guinevere": ["Hadanacido", "Golpeador"],
    "Irithel": ["Juraperdición", "Tirador"],
    "Johnson": ["Eruditio", "Defensor"],
    "Kagura": ["Exorcista", "Mago"],
    "Kaja": ["Señor de Ascuas", "Defensor", "Apoyo"],
    "Karina": ["Poder Astral", "Espadachín"],
    "Layla": ["Eruditio", "Tirador"],
    "Ling": ["Altar del Dragón", "Espadachín"],
    "Lolita": ["Eruditio", "Intrépido"],
    "Lunox": ["Poder Astral", "Astrónomo"],
    "Luo Yi": ["Tejedor de Sombras", "Astrónomo"],
    "Martis": ["Poder Astral", "Maestro de Armas"],
    "Masha": ["Valle del Norte", "Golpeador"],
    "Minotauro": ["Poder Astral", "Defensor"],
    "Moskov": ["Señor de Ascuas", "Tirador"],
    "Natan": ["Eruditio", "Astrónomo"],
    "Nolan": ["Eruditio", "Espadachín"],
    "Odette": ["Poder Astral", "Mago"],
    "Popol y Kupa": ["Valle del Norte", "Invocador"],
    "Sun": ["Altar del Dragón", "Invocador"],
    "Suyou": ["Altar del Dragón", "Maestro de Armas"],
    "Terizla": ["Portador del Amanecer", "Defensor"],
    "Thamuz": ["Señor de Ascuas", "Maestro de Armas"],
    "Uranus": ["Portador del Amanecer", "Intrépido"],
    "Vale": ["Portador del Amanecer", "Mago"],
    "Vexana": ["Portador del Amanecer", "Invocador"],
    "Wanwan": ["Altar del Dragón", "Tirador"],
    "Yu Zhong": ["Exorcista", "Golpeador"],
    "Yve": ["Valle del Norte", "Astrónomo"],
    "Zhask": ["Poder Astral", "Invocador"]
}
